<?php echo $this->doctype();?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	    <link id="themeStyles" rel="stylesheet" href="<?=$this->serverUrl()?>/js/library/dijit/themes/claro/claro.css"/>
	    <link id="themeStyles" rel="stylesheet" href="<?=$this->serverUrl()?>/js/library/dojo/resources/dnd.css"/>
	    <link id="themeStyles" rel="stylesheet" href="<?=$this->serverUrl()?>/js/module/manage/themes/manage/manage.css"/>
    </head>
    <body class="claro">
        <?php echo $this->content; ?>
        <script>
            dojoConfig = {
                // Don't attempt to parse the page for widgets
                parseOnLoad: true,
                packages: [
                    // Any references to a "demo" resource should load modules locally, *not* from CDN
                    {
                        name: "manage",
                        location: "<?=$this->serverUrl()?>/js/module/manage"
                    }
                ],
                // Timeout after 10 seconds
                waitSeconds: 10,
                // Get "fresh" resources
                cacheBust: true
            };
        </script>
        <script src="<?=$this->serverUrl()?>/js/library/dojo/dojo.js"></script>
    </body>
</html>
