<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <?php echo $this->content; ?>
        <script>
            dojoConfig = {
                // Don't attempt to parse the page for widgets
                parseOnLoad: true,
                packages: [
                    // Any references to a "demo" resource should load modules locally, *not* from CDN
                    {
                        name: "manage",
                        location: "<?=$this->basePath()?>/js/module/manage"
                    }
                ],
                // Timeout after 10 seconds
                waitSeconds: 10,
                // Get "fresh" resources
                cacheBust: true
            };
        </script>
        <script src="<?=$this->basePath()?>/js/library/dojo/dojo/dojo.js"></script>
    </body>
</html>
